const masterTeamList = [{
    team: "Saint Louis Arch Bishops",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "Canada Chessbrahs",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Canada",
    division: "Western Division",
 },
 {
    team: "California Unicorns",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "New York Marshalls",
    points: 0,
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "Chicago Wind",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "U.K. Lions",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "UK.",
    division: "Western Division",
 },
 {
    team: "Argentina Krakens",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Argentina",
    division: "Western Division",
},
{
    team: "Brazil Capybaras",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Brazil",
    division: "Western Division",
},
{
    team: "Armenia Eagles",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Arminia",
    division: "Eastern Division",
},
{
    team: "Russia Wizards",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Russia",
    division: "Eastern Division",
},
{
    team: "India Yogis",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "India",
    division: "Eastern Division",
},
{
    team: "China Pandas",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "China",
    division: "Eastern Division",
},
{
    team: "Hungary Hunters",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Hungary",
    division: "Eastern Division",
},
{
    team: "Israel Counsellors",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Isreal",
    division: "Eastern Division",
},
{
    team: "Turkey Knights",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Turkey",
    division: "Eastern Division",
},
{
    team: "Croatia Bulldogs",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Croatia",
    division: "Eastern Division",
},
{
    team: "Germany Bears",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Germany",
    division: "Central Division",
},
{
    team: "France Roosters",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "France",
    division: "Central Division",
},
{
    team: "Norway Gnomes",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Norway",
    division: "Central Division",
},
{
    team: "Sweden Wasabis",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Sweden",
    division: "Central Division",
},
{
    team: "Italy Gladiators",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Italy",
    division: "Central Division",
},
{
    team: "Poland Hussars",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Poland",
    division: "Central Division",
},
{
    team: "Netherlands Mosquitoes",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Netherlands",
    division: "Central Division",
},
{
    team: "Spain Raptors",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Spain",
    division: "Central Division",
}
];