//the initial setup values of all of the teams
const masterTeamList = [{
    team: "Saint Louis Arch Bishops",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "Canada Chessbrahs",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Canada",
    division: "Western Division",
 },
 {
    team: "California Unicorns",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "New York Marshalls",
    points: 0,
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "Chicago Wind",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "USA",
    division: "Western Division",
 },
 {
    team: "U.K. Lions",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "UK.",
    division: "Western Division",
 },
 {
    team: "Argentina Krakens",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Argentina",
    division: "Western Division",
},
{
    team: "Brazil Capybaras",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Brazil",
    division: "Western Division",
},
{
    team: "Armenia Eagles",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Arminia",
    division: "Eastern Division",
},
{
    team: "Russia Wizards",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Russia",
    division: "Eastern Division",
},
{
    team: "India Yogis",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "India",
    division: "Eastern Division",
},
{
    team: "China Pandas",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "China",
    division: "Eastern Division",
},
{
    team: "Hungary Hunters",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Hungary",
    division: "Eastern Division",
},
{
    team: "Israel Counsellors",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Isreal",
    division: "Eastern Division",
},
{
    team: "Turkey Knights",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Turkey",
    division: "Eastern Division",
},
{
    team: "Croatia Bulldogs",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Croatia",
    division: "Eastern Division",
},
{
    team: "Germany Bears",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Germany",
    division: "Central Division",
},
{
    team: "France Roosters",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "France",
    division: "Central Division",
},
{
    team: "Norway Gnomes",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Norway",
    division: "Central Division",
},
{
    team: "Sweden Wasabis",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Sweden",
    division: "Central Division",
},
{
    team: "Italy Gladiators",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Italy",
    division: "Central Division",
},
{
    team: "Poland Hussars",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Poland",
    division: "Central Division",
},
{
    team: "Netherlands Mosquitoes",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Netherlands",
    division: "Central Division",
},
{
    team: "Spain Raptors",
    points: 0,
    wins: 0,
    loses: 0,
    ties: 0,
    country: "Spain",
    division: "Central Division",
}
];

//the initial baked-in values of all of the games
const masterGameList = [{
    homeTeam: "Saint Louis Arch Bishops",
    awayTeam: "U.K. Lions",
    homePoints: 10,
    awayPoints: 6.5,
    result: "win",
    gameDate: "2021-06-04",
},
{
    homeTeam: "Saint Louis Arch Bishops",
    awayTeam: "Canada Chessbrahs",
    homePoints: 7,
    awayPoints: 9.5,
    result: "loss", 
    gameDate: "2021-06-25",
},
{
    homeTeam: "Saint Louis Arch Bishops",
    awayTeam: "India Yogis",
    homePoints: 10,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-07-02",
},
{
    homeTeam: "Saint Louis Arch Bishops",
    awayTeam: "Italy Gladiators",
    homePoints: 9.5,
    awayPoints: 7,
    result: "win", 
    gameDate: "2021-02-05",
},
{
    homeTeam: "Saint Louis Arch Bishops",
    awayTeam: "New York Marshalls",
    homePoints: 6,
    awayPoints: 9,
    result: "loss", 
    gameDate: "2021-01-01",
},
{
    homeTeam: "Canada Chessbrahs",
    awayTeam: "Poland Hussars",
    homePoints: 10,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-01-15",
},
{
    homeTeam: "Canada Chessbrahs",
    awayTeam: "Sweden Wasabis",
    homePoints: 9,
    awayPoints: 0.5,
    result: "win", 
    gameDate: "2021-01-08",
},
{
    homeTeam: "Canada Chessbrahs",
    awayTeam: "Norway Gnomes",
    homePoints: 1.5,
    awayPoints: 10,
    result: "loss",
    gameDate: "2021-04-06",
},
{
    homeTeam: "Canada Chessbrahs",
    awayTeam: "France Roosters",
    homePoints: 8,
    awayPoints: 9,
    result: "loss", 
    gameDate: "2021-10-22",
},
{
    homeTeam: "California Unicorns",
    awayTeam: "Sweden Wasabis",
    homePoints: 10,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-12-17",
},
{
    homeTeam: "California Unicorns",
    awayTeam: "New York Marshalls",
    homePoints: 8.5,
    awayPoints: 8.5,
    result: "tie", 
    gameDate: "2021-05-28",
},
{
    homeTeam: "California Unicorns",
    awayTeam: "Croatia Bulldogs",
    homePoints: 10,
    awayPoints: 7.5,
    result: "win", 
    gameDate: "2021-08-13",
},
{
    homeTeam: "California Unicorns",
    awayTeam: "U.K. Lions",
    homePoints: 9,
    awayPoints: 9,
    result: "tie", 
    gameDate: "2021-10-08",
},
{
    homeTeam: "California Unicorns",
    awayTeam: "Chicago Wind",
    homePoints: 10,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-08-27",
},
{
    homeTeam: "New York Marshalls",
    awayTeam: "France Roosters",
    homePoints: 10,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-04-16",
},
{
    homeTeam: "New York Marshalls",
    awayTeam: "Turkey Knights",
    homePoints: 6,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-02-05",
},
{
    homeTeam: "New York Marshalls",
    awayTeam: "Armenia Eagles",
    homePoints: 8,
    awayPoints: 8.5,
    result: "loss", 
    gameDate: "2021-03-05",
},
{
    homeTeam: "Chicago Wind",
    awayTeam: "Croatia Bulldogs",
    homePoints: 5.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-02-26",
},
{
    homeTeam: "Chicago Wind",
    awayTeam: "Poland Hussars",
    homePoints: 5.5,
    awayPoints: 8.5,
    result: "loss", 
    gameDate: "2021-12-03",
},
{
    homeTeam: "Chicago Wind",
    awayTeam: "Norway Gnomes",
    homePoints: 7,
    awayPoints: 9.5,
    result: "loss", 
    gameDate: "2021-11-26",
},
{
    homeTeam: "Chicago Wind",
    awayTeam: "Argentina Krakens",
    homePoints: 7,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-11-12",
},
{
    homeTeam: "U.K. Lions",
    awayTeam: "Germany Bears",
    homePoints: 8,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-08-27",
},
{
    homeTeam: "U.K. Lions",
    awayTeam: "Italy Gladiators",
    homePoints: 10,
    awayPoints: 4.5,
    result: "win", 
    gameDate: "2021-12-17",
},
{
    homeTeam: "U.K. Lions",
    awayTeam: "Turkey Knights",
    homePoints: 9,
    awayPoints: 9,
    result: "tie", 
    gameDate: "2021-01-22",
},
{
    homeTeam: "Argentina Krakens",
    awayTeam: "Netherlands Mosquitoes",
    homePoints: 8,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-04-23",
},
{
    homeTeam: "Argentina Krakens",
    awayTeam: "Poland Hussars",
    homePoints: 0.5,
    awayPoints: 8.5,
    result: "loss", 
    gameDate: "2021-05-14",
},
{
    homeTeam: "Argentina Krakens",
    awayTeam: "Turkey Knights",
    homePoints: 8,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-02-05",
},
{
    homeTeam: "Argentina Krakens",
    awayTeam: "Armenia Eagles",
    homePoints: 10,
    awayPoints: 7.5,
    result: "win", 
    gameDate: "2021-07-16",
},
{
    homeTeam: "Brazil Capybaras",
    awayTeam: "Italy Gladiators",
    homePoints: 4.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-04-30",
},
{
    homeTeam: "Brazil Capybaras",
    awayTeam: "Sweden Wasabis",
    homePoints: 8.5,
    awayPoints: 6,
    result: "win", 
    gameDate: "2021-06-04",
},
{
    homeTeam: "Brazil Capybaras",
    awayTeam: "China Pandas",
    homePoints: 8,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-11-26",
},
{
    homeTeam: "Brazil Capybaras",
    awayTeam: "Croatia Bulldogs",
    homePoints: 6.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-07-30",
},
{
    homeTeam: "Brazil Capybaras",
    awayTeam: "Israel Counsellors",
    homePoints: 10,
    awayPoints: 3,
    result: "win", 
    gameDate: "2021-10-01",
},
{
    homeTeam: "Armenia Eagles",
    awayTeam: "Hungary Hunters",
    homePoints: 6,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-10-08",
},

{
    homeTeam: "Armenia Eagles",
    awayTeam: "Turkey Knights",
    homePoints: 5.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-03-26",
},
{
    homeTeam: "Armenia Eagles",
    awayTeam: "Sweden Wasabis",
    homePoints: 3.5,
    awayPoints: 9,
    result: "loss", 
    gameDate: "2021-11-05",
},
{
    homeTeam: "Russia Wizards",
    awayTeam: "Israel Counsellors",
    homePoints: 3,
    awayPoints: 8.5,
    result: "loss", 
    gameDate: "2021-10-01",
},
{
    homeTeam: "Russia Wizards",
    awayTeam: "Croatia Bulldogs",
    homePoints: 5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-06-25",
},
{
    homeTeam: "Russia Wizards",
    awayTeam: "Netherlands Mosquitoes",
    homePoints: 7.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-05-28",
},
{
    homeTeam: "Russia Wizards",
    awayTeam: "Turkey Knights",
    homePoints: 7,
    awayPoints: 8.5,
    result: "loss", 
    gameDate: "2021-10-22",
},
{
    homeTeam: "Russia Wizards",
    awayTeam: "Hungary Hunters",
    homePoints: 3.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-01-15",
},
{
    homeTeam: "India Yogis",
    awayTeam: "Italy Gladiators",
    homePoints: 6,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-01-15",
},
{
    homeTeam: "India Yogis",
    awayTeam: "Israel Counsellors",
    homePoints: 8.5,
    awayPoints: 4.5,
    result: "win", 
    gameDate: "2021-04-30",
},
{
    homeTeam: "India Yogis",
    awayTeam: "Norway Gnomes",
    homePoints: 10,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-03-12",
},
{
    homeTeam: "India Yogis",
    awayTeam: "Hungary Hunters",
    homePoints: 10,
    awayPoints: 7,
    result: "win", 
    gameDate: "2021-01-08",
},
{
    homeTeam: "China Pandas",
    awayTeam: "Netherlands Mosquitoes",
    homePoints: 8.5,
    awayPoints: 2,
    result: "win", 
    gameDate: "2021-06-11",
},
{
    homeTeam: "China Pandas",
    awayTeam: "Spain Raptors",
    homePoints: 10,
    awayPoints: 5.5,
    result: "win", 
    gameDate: "2021-06-04",
},
{
    homeTeam: "China Pandas",
    awayTeam: "Norway Gnomes",
    homePoints: 10,
    awayPoints: 7,
    result: "win", 
    gameDate: "2021-09-17",
},
{
    homeTeam: "China Pandas",
    awayTeam: "Germany Bears",
    homePoints: 9.5,
    awayPoints: 4.5,
    result: "win", 
    gameDate: "2021-05-14",
},
{
    homeTeam: "Hungary Hunters",
    awayTeam: "Poland Hussars",
    homePoints: 7,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-05-07",
},
{
    homeTeam: "Hungary Hunters",
    awayTeam: "Italy Gladiators",
    homePoints: 7.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-03-19",
},
{
    homeTeam: "Israel Counsellors",
    awayTeam: "Spain Raptors",
    homePoints: 7.5,
    awayPoints: 10,
    result: "loss", 
    gameDate: "2021-11-05",
},
{
    homeTeam: "Israel Counsellors",
    awayTeam: "Germany Bears",
    homePoints: 8.5,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-01-15",
},
{
    homeTeam: "Croatia Bulldogs",
    awayTeam: "Germany Bears",
    homePoints: 10,
    awayPoints: 6.5,
    result: "win", 
    gameDate: "2021-12-17",
},
{
    homeTeam: "Germany Bears",
    awayTeam: "Spain Raptors",
    homePoints: 6,
    awayPoints: 8.5,
    result: "loss", 
    gameDate: "2021-05-07",
},
{
    homeTeam: "France Roosters",
    awayTeam: "Netherland",
    homePoints: 3.5,
    awayPoints: 8.5,
    result: "loss", 
    gameDate: "2021-09-17",
},
{
    homeTeam: "France Roosters",
    awayTeam: "Spain Raptors",
    homePoints: 10,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-04-02",
},
{
    homeTeam: "France Roosters",
    awayTeam: "Poland Hussars",
    homePoints: 8,
    awayPoints: 9,
    result: "loss", 
    gameDate: "2021-08-06",
},
{
    homeTeam: "Norway Gnomes",
    awayTeam: "Sweden Wasabis",
    homePoints: 9,
    awayPoints: 8,
    result: "win", 
    gameDate: "2021-05-14",
},
{
    homeTeam: "Netherlands Mosquitoes",
    awayTeam: "Spain Raptors",
    homePoints: 10,
    awayPoints: 7,
    result: "win", 
    gameDate: "2021-01-15",
},
];